GET http://localhost:3000/states/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjgwNDM2NTcxfQ.DOaQcEkNwQLz2oqAEmJ3--hfIeKdlCYRIGp32uIWSSA

###

GET http://localhost:3000/states/8/
###



POST http://localhost:3000/districts/

Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/322/

###

DELETE http://localhost:3000/districts/20/
###

PUT http://localhost:3000/districts/2
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000//states/:stateId/stats/

###



POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###